version: '3.4'

services:
#  wallets:
#    image: ${DOCKER_REGISTRY-}wallets
#    build:
#      context: .
#      dockerfile: Wallets/Dockerfile
  db:
    image: postgres:16.0
    restart: always
    container_name: wallets-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./wallets.sql:/docker-entrypoint-initdb.d/001.sql
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4:7.0
    restart: always
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: def@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80